{
 "title": "Stocks",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "stock",
    "label": "Stock",
    "query": "select company from v_stock_value;"
   }
  ]
 },
 "panels": [
  {
   "title": "Percent of selected stocks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select (sum(new.value)/sum(old.value))-1 from \r\n(\r\n  select so.company, jo.value from (\r\n    select company, min(added_at) added_at from v_stock_value group by company\r\n  ) so\r\n  join v_stock_value jo on so.company=jo.company and so.added_at = jo.added_at\r\n) old\r\n,\r\n(\r\n  select sn.company, jn.value from (\r\n    select company, max(added_at) added_at from v_stock_value group by company\r\n  ) sn\r\n  join v_stock_value jn on sn.company=jn.company and sn.added_at=jn.added_at\r\n) new\r\nwhere old.company = new.company and new.company in($stock)"
    }
   ]
  },
  {
   "title": "Absolute of selected stocks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select sum(new.value-old.value) value from \r\n(\r\n  select so.company, jo.value from (\r\n    select company, min(added_at) added_at from v_stock_value group by company\r\n  ) so\r\n  join v_stock_value jo on so.company=jo.company and so.added_at = jo.added_at\r\n) old\r\n,\r\n(\r\n  select sn.company, jn.value from (\r\n    select company, max(added_at) added_at from v_stock_value group by company\r\n  ) sn\r\n  join v_stock_value jn on sn.company=jn.company and sn.added_at=jn.added_at\r\n) new\r\nwhere old.company = new.company and new.company in ($stock)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 0, "y": 2 },
   "repeat": "stock",
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 1.7142857142857142, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 3.4285714285714284, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 5.142857142857142, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 6.857142857142857, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 8.571428571428571, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 10.285714285714285, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 11.999999999999998, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 13.714285714285712, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 15.428571428571425, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 17.14285714285714, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 18.857142857142854, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 20.57142857142857, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 22.285714285714285, "y": 2 },
   "content": "**$stock**",
   "targets": [
    {
     "rawSql": "SELECT\n  date_added AS \"time\",\n  oilwertid\nFROM oil_wert\nWHERE\n  $__timeFilter(date_added)\nORDER BY date_added"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 0, "y": 4 },
   "repeat": "stock",
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 1.7142857142857142, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 3.4285714285714284, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 5.142857142857142, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 6.857142857142857, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 8.571428571428571, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 10.285714285714285, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 11.999999999999998, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 13.714285714285712, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 15.428571428571425, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 17.14285714285714, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 18.857142857142854, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 20.57142857142857, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Absolute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 22.285714285714285, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, diff from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 0, "y": 6 },
   "repeat": "stock",
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 1.7142857142857142, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 3.4285714285714284, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 5.142857142857142, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 6.857142857142857, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 8.571428571428571, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 10.285714285714285, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 11.999999999999998, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 13.714285714285712, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 15.428571428571425, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 17.14285714285714, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 18.857142857142854, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 20.57142857142857, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 22.285714285714285, "y": 6 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "select company, perc from v_profit where company = $stock"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 0, "y": 8 },
   "repeat": "stock",
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 1.7142857142857142, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 3.4285714285714284, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 5.142857142857142, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 6.857142857142857, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 8.571428571428571, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 10.285714285714285, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 11.999999999999998, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 13.714285714285712, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 15.428571428571425, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 17.14285714285714, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 18.857142857142854, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 20.57142857142857, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "TimeRange",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1.7142857142857142, "x": 22.285714285714285, "y": 8 },
   "format": "percentunit",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n\ts.company                               AS company,\n\tROUND((new.value - old.value), 2)       AS diff   ,\n\tROUND(((new.value / old.value) - 1), 4) AS perc\nFROM\n\t((\n\t(\n\t\tSELECT\n\t\t\tso.stock_id AS stock_id,\n\t\t\tjo.value    AS value\n\t\tFROM\n\t\t\t(\n\t\t\t(\n\t\t\t\tSELECT\n\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\tMIN(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\tFROM\n\t\t\t\t\tstock_value\n\t\t\t\twhere $__timeFilter(added_at)\n\t\t\t\tGROUP BY\n\t\t\t\t\tstock_value.stock_id\n\t\t\t)\n\t\t\t`so`\n\t\t\tJOIN\n\t\t\t\tstock_value jo\n\t\t\t\tON\n\t\t\t\t\t(\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_id = jo.stock_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\tso.stock_value_id = jo.stock_value_id\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t\t)\n\t\t\t)\n\t)\n\told\n\tJOIN\n\t\t(\n\t\t\tSELECT\n\t\t\t\tsn.stock_id AS stock_id,\n\t\t\t\tjn.value    AS value\n\t\t\tFROM\n\t\t\t\t(\n\t\t\t\t(\n\t\t\t\t\tSELECT\n\t\t\t\t\t\tstock_value.stock_id            AS stock_id,\n\t\t\t\t\t\tMAX(stock_value.stock_value_id) AS stock_value_id\n\t\t\t\t\tFROM\n\t\t\t\t\t\tstock_value\n\t\t\t\t\tGROUP BY\n\t\t\t\t\t\tstock_value.stock_id\n\t\t\t\t)\n\t\t\t\tsn\n\t\t\t\tJOIN\n\t\t\t\t\tstock_value jn\n\t\t\t\t\tON\n\t\t\t\t\t\t(\n\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_id = jn.stock_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t\tAND\n\t\t\t\t\t\t\t\t(\n\t\t\t\t\t\t\t\t\tsn.stock_value_id = jn.stock_value_id\n\t\t\t\t\t\t\t\t)\n\t\t\t\t\t\t\t)\n\t\t\t\t\t\t)\n\t\t\t\t)\n\t\t)\n\t\tnew)\n\tJOIN\n\t\tstock s)\nWHERE\n\t(\n\t\t(\n\t\t\told.stock_id = new.stock_id\n\t\t)\n\t\tAND\n\t\t(\n\t\t\ts.stock_id = new.stock_id\n\t\t) and company = $stock\n\t)\n;"
    }
   ]
  },
  {
   "title": "Graph of $stock",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  added_at AS \"time\",\n  company AS metric,\n  value\nFROM v_stock_value\nWHERE\n  $__timeFilter(added_at) AND\n  company in($stock)\nORDER BY added_at"
    }
   ]
  }
 ]
}